version: '2'
services:
    mquote-app:
        image: mquote
        external_links:
            - mquote-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mQuote
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mquote-mongodb:
        extends:
            file: mongodb.yml
            service: mquote-mongodb
