version: '2'
services:
    mquote-mongodb:
        container_name: mquote-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/mQuote/mongodb/:/data/db/
